// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdyppWEtpdG_FyuSAnwcJbHj8clvJ3AVE',
    appId: '1:342544453468:android:1288cef4d3500905b67b99',
    messagingSenderId: '342544453468',
    projectId: 'mata-angin-e1f8d',
    storageBucket: 'mata-angin-e1f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6wOuj1LaFwoW7WDnfqHuRUV6m6TSpx4M',
    appId: '1:342544453468:ios:8d79e8f2964eb668b67b99',
    messagingSenderId: '342544453468',
    projectId: 'mata-angin-e1f8d',
    storageBucket: 'mata-angin-e1f8d.firebasestorage.app',
    iosBundleId: 'com.example.frontendMataangin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RIwN1LBnvsnGAXZ5Qcjo_M8Kb3c6by0',
    appId: '1:342544453468:web:60621eace4711b7bb67b99',
    messagingSenderId: '342544453468',
    projectId: 'mata-angin-e1f8d',
    storageBucket: 'mata-angin-e1f8d.firebasestorage.app',
    authDomain: 'mata-angin-e1f8d.firebaseapp.com',
    measurementId: 'G-LL0G9ZLF3J',
  );
}
